// Generated by CoffeeScript 1.7.1
(function() {
  var app, express;

  express = require('express');

  app = express();

  app.get('/hello.txt', (function(_this) {
    return function(req, res) {
      return res.send('Hello World!');
    };
  })(this));

  app.use(express["static"](__dirname + '/public'));

  app.listen('4000');

  console.log('running on 120.0.0.1 listening to port 4000');

}).call(this);
